# Generated by Django 5.0.1 on 2024-01-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_sku_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
